version: "3"
services:
  eureka:
    image: eureka-server
    ports:
      - "8761:8761"
    build:
      context: ./discoveryserver
      dockerfile: Dockerfile
    environment:
      EUREKASERVER_URI: "http://eureka-server:8761/eureka/"
      EUREKASERVER_PORT: "8761"
    networks:
      - eureka-integration
  
  amazon:
    image: amazon-shopping
    environment:
        - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka"
    ports:
      - "9999:9999"
    networks:
      - eureka-integration
    depends_on:
       - eureka 
  
  payment:
    image: payment-service
    environment:
        - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka"
    ports:
      - "8888:8888"
    networks:
      - eureka-integration
    depends_on:
       - eureka 

networks:
  eureka-integration:
