version: "3"
services:
  eureka:
    # image: eureka-server
    build : ./eureka-server
    # dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - eureka-integration
  
  amazon:
    # image: amazon-shopping
    build : ./amazon-shopping
    # dockerfile : Dockerfile
    ports:
      - "9999:9999"
    networks:
      - eureka-integration
    depends_on:
       - eureka 
  
  payment:
    # image: payment-service
    build : ./payment-service
   # dockerfile : Dockerfile
    ports:
      - "8888:8888"
    networks:
      - eureka-integration
    depends_on:
       - eureka 

networks:
  eureka-integration:
