eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://github-microservice-docker-integration-eureka-1:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8888
spring:
  application:
    name: PAYMENT-SERVICE
    
    
    
    
