eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 9999
spring:
  application:
    name: SHOPPING-SERVICE
